import * as _ from 'lodash';
import React from 'react';

export const VIEWS = _.keyBy([
  // Room A
  'ROOM_A_FULL',
  'ROOM_A_COMPUTER',
  'ROOM_A_LOCKER',
  'ROOM_A_LOCKER_UNLOCKED',
  'ROOM_A_DOOR',
  'ROOM_A_WALL',

  // Room B
  'ROOM_B_FULL',
  'ROOM_B_LOCKED_BOX',
  'ROOM_B_OPEN_BOX',
  'ROOM_B_SCREENS',
  'ROOM_B_MONITOR_1',
  'ROOM_B_MONITOR_2',
  'ROOM_B_MONITOR_3',
  'ROOM_B_MONITOR_4',

  // Room C
  'ROOM_C_FULL',
  'ROOM_C_BOXES',
  'ROOM_C_DOOR',
  'ROOM_C_EXIT',
  'ROOM_C_TILE_1',
  'ROOM_C_TILE_2',

  // Room D
  'ROOM_D_FULL',
  'ROOM_D_BROKEN',
  'ROOM_D_SWITCH',
  'ROOM_D_DOOR',

  // Room E
  'ROOM_E_FULL',
  'ROOM_E_CABINET',
  'ROOM_E_HOOD',
  'ROOM_E_WALL',
  'ROOM_E_WALL_UNLOCKED',
  'ROOM_E_COUNTER',

  // Exit
  'EXIT',
]);

export const BACK_NAV_MAP = {
  // Room A
  [VIEWS.ROOM_A_FULL]: null,
  [VIEWS.ROOM_A_COMPUTER]: VIEWS.ROOM_A_FULL,
  [VIEWS.ROOM_A_LOCKER]: VIEWS.ROOM_A_FULL,
  [VIEWS.ROOM_A_LOCKER_UNLOCKED]: VIEWS.ROOM_A_FULL,
  [VIEWS.ROOM_A_DOOR]: VIEWS.ROOM_A_FULL,
  [VIEWS.ROOM_A_WALL]: VIEWS.ROOM_A_FULL,

  // Room B
  [VIEWS.ROOM_B_FULL]: VIEWS.ROOM_A_FULL,
  [VIEWS.ROOM_B_LOCKED_BOX]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_OPEN_BOX]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_SCREENS]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_MONITOR_1]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_MONITOR_2]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_MONITOR_3]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_B_MONITOR_4]: VIEWS.ROOM_B_FULL,

  // Room C
  [VIEWS.ROOM_C_FULL]: VIEWS.ROOM_B_FULL,
  [VIEWS.ROOM_C_BOXES]: VIEWS.ROOM_C_FULL,
  [VIEWS.ROOM_C_DOOR]: VIEWS.ROOM_C_FULL,
  [VIEWS.ROOM_C_EXIT]: VIEWS.ROOM_C_FULL,
  [VIEWS.ROOM_C_TILE_1]: VIEWS.ROOM_C_FULL,
  [VIEWS.ROOM_C_TILE_2]: VIEWS.ROOM_C_FULL,

  // Room D
  [VIEWS.ROOM_D_FULL]: VIEWS.ROOM_C_FULL,
  [VIEWS.ROOM_D_BROKEN]: VIEWS.ROOM_D_FULL,
  [VIEWS.ROOM_D_SWITCH]: VIEWS.ROOM_D_FULL,
  [VIEWS.ROOM_D_DOOR]: VIEWS.ROOM_D_FULL,

  // Room E
  [VIEWS.ROOM_E_FULL]: VIEWS.ROOM_D_FULL,
  [VIEWS.ROOM_E_CABINET]: VIEWS.ROOM_E_FULL,
  [VIEWS.ROOM_E_HOOD]: VIEWS.ROOM_E_FULL,
  [VIEWS.ROOM_E_WALL]: VIEWS.ROOM_E_FULL,
  [VIEWS.ROOM_E_WALL_UNLOCKED]: VIEWS.ROOM_E_FULL,
  [VIEWS.ROOM_E_COUNTER]: VIEWS.ROOM_E_FULL,

  // Exit
  [VIEWS.EXIT]: null,
};

export const AppContext = React.createContext({
  name: '',
  view: '',
  setFields: () => {},
  goBack: () => {},
});
